export const dataDummy = [
  {
    id: 1321,
    induk_id: 1321,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Komposisi Portofolio Aset termasuk jenis akad yang digunakan dan Tingkat Konsentrasi",
    level: 1,
    penomoran: "1",
    id_jenis_nilai: 1,
  },
  {
    id: 1322,
    risk_id: 45,
    induk_id: 1321,
    parameter_faktor_id: 1321,
    bulan: 6,
    tahun: 2020,
    name: "Pembiayaan kepada Debitur Inti/ Total Pembiayaan",
    level: 2,
    penomoran: "a",
    id_jenis_nilai: 1,
  },
  {
    id: 1323,
    risk_id: 45,
    induk_id: 1321,
    parameter_faktor_id: 1321,
    name: "Pembiayaan kepada Debitur inti/Total Pembiayaan",
    bulan: 6,
    tahun: 2020,
    value: "M",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "≤ 10%",
    pr_lowtomod : "10% < x ≤ 15%",
    pr_mod : "15% < x ≤ 20%",
    pr_modtohigh : "20% < x ≤ 25%",
    pr_high : "> 25%",
    ratio : "17.42%",
    risk_rate : "M",
    score : 3.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "1",
    bobot: "100%",
    bobot_score: 3.0,
  },
  {
    id: 1324,
    risk_id: 45,
    induk_id: 1321,
    parameter_faktor_id: 1321,
    bulan: 6,
    tahun: 2020,
    name: "Pembiayaan per Sektor Ekonomi/Total Pembiayaan",
    level: 2,
    penomoran: "b",
    id_jenis_nilai: 1,
  },
  {
    id: 1325,
    risk_id: 45,
    induk_id: 1324,
    parameter_faktor_id: 1321,
    name: "Pertanian, perburuan dan kehutanan",
    bulan: 6,
    tahun: 2020,
    value: "M",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "< 0.37%",
    pr_lowtomod : "0.0037<x≤0.0038",
    pr_mod : "0.0038<x≤0.0039",
    pr_modtohigh : "0.0039<x≤0.0041",
    pr_high : "x>0.0041%",
    ratio : "0.2%",
    risk_rate : "L",
    score : 1.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "1",
    bobot: "1.00%",
    bobot_score: 0.2
  },
  {
    id: 1326,
    risk_id: 45,
    induk_id: 1324,
    parameter_faktor_id: 1321,
    name: "Perikanan",
    bulan: 6,
    tahun: 2020,
    value: "H",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "< 0.04%",
    pr_lowtomod : "0.0004<x≤0.0005",
    pr_mod : "0.0005<x≤0.0005",
    pr_modtohigh : "0.0005<x≤0.0006",
    pr_high : "x>0.0006",
    ratio : "4%",
    risk_rate : "H",
    score : 5.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "2",
    bobot: "4.00%",
    bobot_score: 0.2
  },{
    id: 1611,
    risk_id: 45,
    induk_id: 1321,
    parameter_faktor_id: 1321,
    bulan: 6,
    tahun: 2020,
    name: "Aset dan TRA Kualitas Rendah",
    level: 2,
    penomoran: "c",
    id_jenis_nilai: 1,
  },
  {
    id: 1612,
    risk_id: 45,
    induk_id: 1611,
    parameter_faktor_id: 1321,
    name: "Aset dan TRA Kualitas Rendah/ Total Aset Gross dan TRA n",
    bulan: 6,
    tahun: 2020,
    value: "M",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "≤ 10%",
    pr_lowtomod : "10% < x ≤ 15%",
    pr_mod : "15% < x ≤ 20%",
    pr_modtohigh : "20% < x ≤ 25%",
    pr_high : "> 25%",
    ratio : "17.42%",
    risk_rate : "M",
    score : 3.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "1",
    bobot: "100%",
    bobot_score: 3.0,
  },
  {
    id: 1324,
    risk_id: 45,
    induk_id: 1321,
    parameter_faktor_id: 1321,
    bulan: 6,
    tahun: 2020,
    name: "Pembiayaan per Sektor Ekonomi/Total Pembiayaan",
    level: 2,
    penomoran: "d",
    id_jenis_nilai: 1,
  },
  {
    id: 1325,
    risk_id: 45,
    induk_id: 1324,
    parameter_faktor_id: 1321,
    name: "Pertanian, perburuan dan kehutanan",
    bulan: 6,
    tahun: 2020,
    value: "M",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "< 0.37%",
    pr_lowtomod : "0.0037<x≤0.0038",
    pr_mod : "0.0038<x≤0.0039",
    pr_modtohigh : "0.0039<x≤0.0041",
    pr_high : "x>0.0041%",
    ratio : "0.2%",
    risk_rate : "L",
    score : 1.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "1",
    bobot: "1.00%",
    bobot_score: 0.2
  },
  {
    id: 1326,
    risk_id: 45,
    induk_id: 1324,
    parameter_faktor_id: 1321,
    name: "Perikanan",
    bulan: 6,
    tahun: 2020,
    value: "H",
    risk_name : "Risiko Kredit",
    pr_low_name : "",
    pr_lowtomod_name : "",
    pr_mod_name : "",
    pr_modtohigh_name : "",
    pr_high_name : "",
    pr_low : "< 0.04%",
    pr_lowtomod : "0.0004<x≤0.0005",
    pr_mod : "0.0005<x≤0.0005",
    pr_modtohigh : "0.0005<x≤0.0006",
    pr_high : "x>0.0006",
    ratio : "4%",
    risk_rate : "H",
    score : 5.0,
    id_jenis_nilai: 1,
    level: 3,
    penomoran: "2",
    bobot: "4.00%",
    bobot_score: 0.2
  },
  {
    parameter_faktor_id: 1321,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Rating Per Faktor",
    level: "Per Faktor",
    penomoran: "",
    bobot: "10%",
    bobot_score: "0.30",
    id_jenis_nilai: 1,
  },
  {
    id: 1330,
    induk_id: 1320,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Strategi Penyediaan Dana dan Sumber Timbulnya Penyediaan Dana",
    level: 1,
    penomoran: "2",
    id_jenis_nilai: 21,
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "Proses Penyediaan dana, tingkat kompetisi dan tingkat pertumbuhan aset",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "LTM",
    score : 2,
    id_jenis_nilai: 21,
    level: 2,
    penomoran: "a",
    bobot: "80%",
    bobot_score: 1.6
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "Proses PenyediaBJBS memiliki standar prosedur operasi untuk proses pemberian pinjaman secara end-to-end untuk menilai tindakan mana yang telah dilaksanakan secara konsisten",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "1",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Ya",
    penomoran: "1",
    bobot: "33%"
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "BJBS adalah salah satu market leader pada industri perbankan syariah berdasarkan total aset dan perkembangan bisnis",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "0",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Tidak",
    penomoran: "2",
    bobot: "33%"
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "Tingkat pertumbuhan aset BJBS diatas rata-rata industri",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "1",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Ya",
    penomoran: "3",
    bobot: "33%"
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "Signifikansi penyediaan dana yang dilakukan oleh bank secara tidak langsung (Channeling /indirect)",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "L",
    score : 1,
    id_jenis_nilai: 21,
    level: 2,
    penomoran: "b",
    bobot: "10%",
    bobot_score: 0.1
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "BJBS menganalisa tujuan untuk setiap pemberian kredit/penyediaan dana",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "1",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Ya",
    penomoran: "1",
    bobot: "33%"
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "BJBS menganalisa dan memahami pihak lawan (counterpart) yang akan menerima dana",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "1",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Ya",
    penomoran: "2",
    bobot: "33%"
  },
  {
    id: 1331,
    risk_id: 45,
    induk_id: 1330,
    parameter_faktor_id: 1330,
    name: "BJBS menganalisa dan memahami pihak lawan (counterpart) yang akan menerima dana",
    bulan: 6,
    tahun: 2020,
    risk_name : "Risiko Kredit",
    risk_rate : "1",
    id_jenis_nilai: 21,
    level: 3,
    ratio: "Ya",
    penomoran: "3",
    bobot: "33%"
  },
  {
    parameter_faktor_id: 1321,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Rating Per Faktor",
    level: "Per Faktor",
    penomoran: "",
    risk_rate : "LTM",
    bobot: "10%",
    bobot_score: "0.30",
    score: 3.0,
    id_jenis_nilai: 21,
  },
  {
    id: 1330,
    induk_id: 1320,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Strategi dan Kebijakan Bisnis",
    level: 1,
    penomoran: "3",
    id_jenis_nilai: 4,
  },
  {
    id: 1380,
    risk_id: 3,
    induk_id: 1380,
    name: "Karakteristik aktivitas bisnis yang berdampak pada risiko benchmark suku bunga dalam banking book dan karakteristik nasabah utama Bank Note : deposito spesial nisbah (nisbah > 49, posisi September 2016 sebesar 92.42%)",
    level: 2,
    penomoran: "a",
    pr_low: "256",
    pr_lowtomod: "255",
    pr_mod: "257",
    pr_modtohigh: "258",
    pr_high: "259",
    bobot: 30,
    id_jenis_nilai: 4,
    bulan: 6,
    tahun: 2020,
    parameter_faktor_id: 1330,
    risk_name: "Risiko Pasar",
    pr_low_name: "Deposito spesial nisbah ≤ 20% dari total deposito non bank",
    pr_lowtomod_name: "Deposito spesial nisbah > 20% sd 40% dari total deposito non bank",
    pr_mod_name: "Deposito spesial nisbah > 40% sd 60% dari total deposito non bank",
    pr_modtohigh_name: "Deposito spesial nisbah > 60% sd 80% dari total deposito non bank",
    pr_high_name: "Deposito spesial nisbah > 80% dari total deposito non bank",
    ratio: "Deposito spesial nisbah > 80% dari total deposito non bank",
    bobot: "40%",
    score : 5.0,
    risk_rate : "LTM",
    bobot_score: 0.2
  },
  {
    id: 1380,
    risk_id: 3,
    induk_id: 1380,
    name: "Posisi pasar Bank dalam industri",
    level: 2,
    penomoran: "b",
    pr_low: "256",
    pr_lowtomod: "255",
    pr_mod: "257",
    pr_modtohigh: "258",
    pr_high: "259",
    bobot: 30,
    id_jenis_nilai: 4,
    bulan: 6,
    tahun: 2020,
    parameter_faktor_id: 1330,
    risk_name: "Risiko Pasar",
    pr_low_name: "Pertumbuhan Dana Murah > Pertumbuhan Perbankan kompetitor",
    pr_lowtomod_name: "Pertumbuhan Dana Murah = Pertumbuhan Perbankan Kompetitor",
    pr_mod_name: "Pertumbuhan Dana Murah < Pertumbuhan Perbankan Kompetitor",
    pr_modtohigh_name: "Dana Murah Bank mengalami penurunan namun masih lebih baik dibandingkan penurunan perbankan kompetitor",
    pr_high_name: "Dana Murah Bank mengalami penurunan dan berada di bawah penurunan perbankan nasional",
    ratio: "Pertumbuhan Dana Murah > Pertumbuhan Perbankan kompetitor",
    bobot: "30%",
    score : 1.0,
    risk_rate : "L",
    bobot_score: 0.3
  },
  {
    id: 1380,
    risk_id: 3,
    induk_id: 1380,
    name: "Karakteristik Nasabah yang sensitif terhadap risiko suku bunga",
    level: 2,
    penomoran: "b",
    pr_low: "256",
    pr_lowtomod: "255",
    pr_mod: "257",
    pr_modtohigh: "258",
    pr_high: "259",
    bobot: 30,
    id_jenis_nilai: 4,
    bulan: 6,
    tahun: 2020,
    parameter_faktor_id: 1330,
    risk_name: "Risiko Pasar",
    pr_low_name: "Nasabah utama Bank tidak sensitif terhadap perubahan suku bunga (pricing)",
    pr_lowtomod_name: "Nasabah utama Bank kurang sensitif terhadap perubahan suku bunga (pricing)",
    pr_mod_name: "Nasabah utama Bank cukup sensitif terhadap perubahan suku bunga (pricing)",
    pr_modtohigh_name: "Nasabah utama Bank sensitif terhadap perubahan suku bunga (pricing)",
    pr_high_name: "Nasabah utama Bank sangat sensitif terhadap perubahan suku bunga (pricing)",
    ratio: "Nasabah utama Bank sangat sensitif terhadap perubahan suku bunga (pricing)",
    bobot: "30%",
    score : 3.0,
    risk_rate : "M",
    bobot_score: 0.9
  },
  {
    parameter_faktor_id: 1321,
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Rating Per Faktor",
    level: "Per Faktor",
    penomoran: "",
    risk_rate : "LTM",
    bobot: "10%",
    bobot_score: "0.30",
    score: 3.0,
    id_jenis_nilai: 4,
  },
  {
    risk_id: 45,
    bulan: 6,
    tahun: 2020,
    name: "Tingkat Risiko Inheren",
    level: "inheren",
    risk_rate : "H",
    bobot_score: "0.30"
  },
]
