// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'SIGNIN_GITHUB_USER_SUCCESS';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'USER_DATA';
export const USER_TOKEN_SET = 'USER_TOKEN_SET';

//Parameter const
export const GET_ALL_PARAMETER_FAKTOR_TABLE = [];
export const GET_PARAMETER_FAKTOR = [];
export const PUT_PARAMETER_FAKTOR = [];
export const POST_PARAMETER_FAKTOR = [];
export const JENIS_NILAI_PARAM = [];
export const GET_ALL_PARAMETER_FAKTOR = [];
export const DELETE_PARAMETER_FAKTOR = 'DELETE_PARAMETER_FAKTOR';
export const STATUS_POST_PARAMETER_FAKTOR = 'STATUS_POST_PARAMETER_FAKTOR';
export const STATUS_PUT_PARAMETER_FAKTOR = 'STATUS_PUT_PARAMETER_FAKTOR';
export const STATUS_ALL_PARAMETER_FAKTOR_TABLE = 'STATUS_ALL_PARAMETER_FAKTOR_TABLE';
export const STATUS_ALL_PARAMETER_FAKTOR = 'STATUS_ALL_PARAMETER_FAKTOR';
export const COUNT_ALL_PARAMETER_FAKTOR = 'COUNT_ALL_PARAMETER_FAKTOR';

//JenisRisiko const
export const GET_ALL_RISKS = [];
export const GET_RISK = [];
export const POST_ALL_RISKS = [];
export const PUT_ALL_RISKS = [];
export const DELETE_ALL_RISKS = 'DELETE_ALL_RISK';
export const STATUS_POST_RISK = 'STATUS_POST_RISK';
export const STATUS_PUT_RISK = 'STATUS_PUT_RISK';
export const STATUS_ALL_RISKS = 'STATUS_ALL_RISKS';
export const COUNT_ALL_RISKS = 'COUNT_ALL_RISKS';
export const STATUS_ALL_RISK = 'STATUS_ALL_RISK';

//PeringkatRisiko const
export const GET_ALL_PERINGKAT_RISIKO = [];
export const GET_PERINGKAT_RISIKO = [];
export const POST_PERINGKAT_RISIKO = [];
export const PUT_PERINGKAT_RISIKO = [];
export const DELETE_PERINGKAT_RISIKO = 'DELETE_PERINGKAT_RISIKO';
export const STATUS_POST_PERINGKAT_RISIKO = 'STATUS_POST_PERINGKAT_RISIKO';
export const STATUS_PUT_PERINGKAT_RISIKO = 'STATUS_PUT_PERINGKAT_RISIKO';
export const STATUS_ALL_PERINGKAT_RISIKO = 'STATUS_PERINGKAT_RISIKO';
export const STATUS_ALL_PERINGKAT_RISIKO_TABLE = 'STATUS_PERINGKAT_RISIKO_TABLE';
export const COUNT_PERINGKAT_RISIKO = 'COUNT_PERINGKAT_RISIKO';

//JenisPenilaian const
export const GET_ALL_JENIS_PENILAIAN = [];
export const GET_JENIS_PENILAIAN = [];
export const POST_JENIS_PENILAIAN = [];
export const PUT_JENIS_PENILAIAN = [];
export const DELETE_JENIS_PENILAIAN = 'DELETE_JENIS_PENILAIAN';
export const STATUS_POST_JENIS_PENILAIAN = 'STATUS_POST_JENIS_PENILAIAN';
export const STATUS_PUT_JENIS_PENILAIAN = 'STATUS_PUT_JENIS_PENILAIAN';
export const STATUS_ALL_JENIS_PENILAIAN = 'STATUS_ALL_JENIS_PENILAIAN';
export const STATUS_ALL_JENIS_PENILAIAN_TABLE = 'STATUS_ALL_JENIS_PENILAIAN_TABLE';
export const COUNT_JENIS_PENILAIAN = 'COUNT_JENIS_PENILAIAN';

//RatioIndikator const
export const GET_ALL_RATIO_INDIKATOR_TABLE = [];
export const GET_RATIO_INDIKATOR = [];
export const GET_ALL_RATIO_INDIKATOR = [];
export const POST_RATIO_INDIKATOR = [];
export const PUT_RATIO_INDIKATOR = [];
export const GET_ALL_RATIO_INDIKATOR_KUALITATIF = [];
export const DELETE_RATIO_INDIKATOR = 'DELETE_RATIO_INDIKATOR';
export const STATUS_POST_RATIO_INDIKATOR = 'STATUS_POST_RATIO_INDIKATOR';
export const STATUS_PUT_RATIO_INDIKATOR = 'STATUS_PUT_RATIO_INDIKATOR';
export const STATUS_ALL_RATIO_INDIKATOR = 'STATUS_ALL_RATIO_INDIKATOR';
export const STATUS_ALL_RATIO_INDIKATOR_TABLE = 'STATUS_ALL_RATIO_INDIKATOR_TABLE';
export const COUNT_RATIO_INDIKATOR = 'COUNT_RATIO_INDIKATOR';

//ParameterManual const
export const GET_ALL_PARAMETER_MANUAL = [];
export const GET_PARAMETER_MANUAL = [];
export const POST_PARAMETER_MANUAL = [];
export const PUT_PARAMETER_MANUAL = [];
export const DELETE_PARAMETER_MANUAL = 'DELETE_PARAMETER_MANUAL';
export const STATUS_POST_PARAMETER_MANUAL = 'STATUS_POST_PARAMETER_MANUAL';
export const STATUS_PUT_PARAMETER_MANUAL = 'STATUS_PUT_PARAMETER_MANUAL';
export const STATUS_ALL_PARAMETER_MANUAL_TABLE = 'STATUS_ALL_PARAMETER_MANUAL_TABLE';
export const STATUS_ALL_PARAMETER_MANUAL = 'STATUS_ALL_PARAMETER_MANUAL';
export const COUNT_PARAMETER_MANUAL = 'COUNT_PARAMETER_MANUAL';

// ParameterKuantitatif const
export const UPDATE_PARAMETER_KUANTITATIF = 'UPDATE_PARAMETER_KUANTITATIF';
export const ADD_PARAMETER_KUANTITATIF = 'ADD_PARAMETER_KUANTITATIF';
export const DELETE_PARAMETER_KUANTITATIF = 'DELETE_PARAMETER_KUANTITATIF';
export const COUNT_PARAMETER_KUANTATIF = 'COUNT_PARAMETER_KUANTATIF';
export const FETCH_ALL_PARAMETER_KUANTITATIF_REQUEST = 'FETCH_ALL_PARAMETER_KUANTITATIF_REQUEST';
export const FETCH_ALL_PARAMETER_KUANTITATIF_SUCCESS = 'FETCH_ALL_PARAMETER_KUANTITATIF_SUCCESS';
export const FETCH_ALL_PARAMETER_KUANTITATIF_FAILURE = 'FETCH_ALL_PARAMETER_KUANTITATIF_FAILURE';
export const GET_PARAMETER_KUANTITATIF = 'GET_PARAMETER_KUANTITATIF';


// ParameterKualitatif const
export const UPDATE_PARAMETER_KUALITATIF = 'UPDATE_PARAMETER_KUALITATIF';
export const ADD_PARAMETER_KUALITATIF = 'ADD_PARAMETER_KUALITATIF';
export const DELETE_PARAMETER_KUALITATIF = 'DELETE_PARAMETER_KUALITATIF';
export const COUNT_PARAMETER_KUALITATIF = 'COUNT_PARAMETER_KUALITATIF';
export const FETCH_ALL_PARAMETER_KUALITATIF_REQUEST = 'FETCH_ALL_PARAMETER_KUALITATIF_REQUEST';
export const FETCH_ALL_PARAMETER_KUALITATIF_SUCCESS = 'FETCH_ALL_PARAMETER_KUALITATIF_SUCCESS';
export const FETCH_ALL_PARAMETER_KUALITATIF_FAILURE = 'FETCH_ALL_PARAMETER_KUALITATIF_FAILURE';
export const GET_PARAMETER_KUALITATIF = 'GET_PARAMETER_KUALITATIF';

// ingredients
export const FETCH_ALL_INGREDIENTS_REQUEST = 'FETCH_ALL_INGREDIENTS_REQUEST';
export const FETCH_ALL_INGREDIENTS_FAILURE = 'FETCH_ALL_INGREDIENTS_FAILURE';
export const FETCH_ALL_INGREDIENTS_SUCCESS = 'FETCH_ALL_INGREDIENTS_SUCCESS';

// Risiko Inheren Ratio Indikator
export const GET_ALL_RISIKO_INHEREN_RATIO_INDIKATOR = [];
export const GET_RISIKO_INHEREN_RATIO_INDIKATOR = [];
export const PUT_RISIKO_INHEREN_RATIO_INDIKATOR = [];
export const POST_RISIKO_INHEREN_RATIO_INDIKATOR = [];
export const STATUS_POST_RISIKO_INHEREN_RATIO_INDIKATOR = 'STATUS_POST_RISIKO_INHEREN_RATIO_INDIKATOR';
export const DELETE_RISIKO_INHEREN_RATIO_INDIKATOR = 'DELETE_RISIKO_INHEREN_RATIO_INDIKATOR';
export const STATUS_ALL_RISIKO_INHEREN_RATIO_INDIKATOR_TABLE = 'STATUS_ALL_RISIKO_INHEREN_RATIO_INDIKATOR_TABLE';
export const STATUS_ALL_RISIKO_INHEREN_RATIO_INDIKATOR = 'STATUS_ALL_RISIKO_INHEREN_RATIO_INDIKATOR';
export const COUNT_RISIKO_INHEREN_RATIO_INDIKATOR = 'COUNT_RISIKO_INHEREN_RATIO_INDIKATOR';
export const STATUS_PUT_RISIKO_INHEREN_RATIO_INDIKATOR = 'STATUS_PUT_RISIKO_INHEREN_RATIO_INDIKATOR';

// Master Version
export const UPDATE_MASTER_VERSION = 'UPDATE_MASTER_VERSION';
export const ADD_MASTER_VERSION = 'ADD_MASTER_VERSION';
export const DELETE_MASTER_VERSION = 'DELETE_MASTER_VERSION';
export const COUNT_MASTER_VERSION = 'COUNT_MASTER_VERSION';
export const FETCH_ALL_MASTER_VERSION_REQUEST = 'FETCH_ALL_MASTER_VERSION_REQUEST';
export const FETCH_ALL_MASTER_VERSION_SUCCESS = 'FETCH_ALL_MASTER_VERSION_SUCCESS';
export const FETCH_ALL_MASTER_VERSION_FAILURE = 'FETCH_ALL_MASTER_VERSION_FAILURE';
export const GET_MASTER_VERSION = 'GET_MASTER_VERSION';

// Parameter Version
export const FETCH_ALL_PARAMETER_VERSION_REQUEST = 'FETCH_ALL_PARAMETER_VERSION_REQUEST';
export const FETCH_ALL_PARAMETER_VERSION_SUCCESS = 'FETCH_ALL_PARAMETER_VERSION_SUCCESS';
export const FETCH_ALL_PARAMETER_VERSION_FAILURE = 'FETCH_ALL_PARAMETER_VERSION_FAILURE';
export const COUNT_PARAMETER_VERSION = 'COUNT_PARAMETER_VERSION';
export const ADD_PARAMETER_VERSION = 'ADD_PARAMETER_VERSION';
export const DELETE_PARAMETER_VERSION = 'DELETE_PARAMETER_VERSION';

// Ratio Indikator Formula
export const FETCH_ALL_RATIO_INDIKATOR_FORMULA_REQUEST = 'FETCH_ALL_RATIO_INDIKATOR_FORMULA_REQUEST';
export const FETCH_ALL_RATIO_INDIKATOR_FORMULA_SUCCESS = 'FETCH_ALL_RATIO_INDIKATOR_FORMULA_SUCCESS';
export const FETCH_ALL_RATIO_INDIKATOR_FORMULA_FAILURE = 'FETCH_ALL_RATIO_INDIKATOR_FORMULA_FAILURE';
export const COUNT_RATIO_INDIKATOR_FORMULA = 'COUNT_RATIO_INDIKATOR_FORMULA';
export const ADD_RATIO_INDIKATOR_FORMULA = 'ADD_RATIO_INDIKATOR_FORMULA';
export const DELETE_RATIO_INDIKATOR_FORMULA = 'DELETE_RATIO_INDIKATOR_FORMULA';
export const GET_RATIO_INDIKATOR_FORMULA = 'GET_RATIO_INDIKATOR_FORMULA';
export const UPDATE_RATIO_INDIKATOR_FORMULA = 'UPDATE_RATIO_INDIKATOR_FORMULA';

// Parameter Kualitatif General
export const FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_REQUEST = 'FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_REQUEST';
export const FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_SUCCESS = 'FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_SUCCESS';
export const FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_FAILURE = 'FETCH_ALL_PARAMETER_KUALITATIF_DUAL_ALTERNATIF_FAILURE';
export const COUNT_PARAMETER_KUALIATIF_DUAL_ALTERNATIF = 'COUNT_PARAMETER_KUALIATIF_DUAL_ALTERNATIF';
export const ADD_PARAMETER_KUALITATIF_DUAL_ALTERNATIF = 'ADD_PARAMETER_KUALITATIF_DUAL_ALTERNATIF';
export const DELETE_PARAMETER_KUALITATIF_DUAL_ALTERNATIF = 'DELETE_PARAMETER_KUALITATIF_DUAL_ALTERNATIF';
export const GET_PARAMETER_KUALITATIF_DUAL_ALTERNATIF = 'GET_PARAMETER_KUALITATIF_DUAL_ALTERNATIF';
export const UPDATE_PARAMETER_KUALITATIF_DUAL_ALTERNATIF = 'UPDATE_PARAMETER_KUALITATIF_DUAL_ALTERNATIF';

// *** KPMR *** KUALITAS PENERAPAN MANAJEMEN RISIKO
// Parameter Kualitatif
// Parameter Kualitatif General
export const KPMR_FETCH_ALL_PARAMETER_KUALITATIF_REQUEST = 'KPMR_FETCH_ALL_PARAMETER_KUALITATIF_REQUEST';
export const KPMR_FETCH_ALL_PARAMETER_KUALITATIF_SUCCESS = 'KPMR_FETCH_ALL_PARAMETER_KUALITATIF_SUCCESS';
export const KPMR_FETCH_ALL_PARAMETER_KUALITATIF_FAILURE = 'KPMR_FETCH_ALL_PARAMETER_KUALITATIF_FAILURE';
export const KPMR_COUNT_PARAMETER_KUALIATIF = 'KPMR_COUNT_PARAMETER_KUALIATIF';
export const KPMR_ADD_PARAMETER_KUALITATIF = 'KPMR_ADD_PARAMETER_KUALITATIF';
export const KPMR_DELETE_PARAMETER_KUALITATIF = 'KPMR_DELETE_PARAMETER_KUALITATIF';
export const KPMR_GET_PARAMETER_KUALITATIF = 'KPMR_GET_PARAMETER_KUALITATIF';
export const KPMR_UPDATE_PARAMETER_KUALITATIF = 'KPMR_UPDATE_PARAMETER_KUALITATIF';


// input data RISIKO INHEREN
// Kuantitatif
export const RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_REQUEST = 'RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_REQUEST';
export const RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_SUCCESS = 'RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_SUCCESS';
export const RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_FAILURE = 'RISIKO_INHEREN_FETCH_INPUT_KUANTITATIF_FAILURE';
export const RISIKO_INHEREN_COUNT_INPUT_KUANTITATIF = 'RISIKO_INHEREN_COUNT_INPUT_KUANTITATIF';
export const RISIKO_INHEREN_ADD_INPUT_KUANTITATIF = 'RISIKO_INHEREN_ADD_INPUT_KUANTITATIF';
export const RISIKO_INHEREN_DELETE_INPUT_KUANTITATIF = 'RISIKO_INHEREN_DELETE_INPUT_KUANTITATIF';
export const RISIKO_INHEREN_GET_INPUT_KUANTITATIF = 'RISIKO_INHEREN_GET_INPUT_KUANTITATIF';
export const RISIKO_INHEREN_UPDATE_INPUT_KUANTITATIF = 'RISIKO_INHEREN_UPDATE_INPUT_KUANTITATIF';

// Kualitatif
export const RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_REQUEST = 'RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_REQUEST';
export const RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_SUCCESS = 'RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_SUCCESS';
export const RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_FAILURE = 'RISIKO_INHEREN_FETCH_INPUT_KUALITATIF_FAILURE';
export const RISIKO_INHEREN_COUNT_INPUT_KUALITATIF = 'RISIKO_INHEREN_COUNT_INPUT_KUALITATIF';
export const RISIKO_INHEREN_ADD_INPUT_KUALITATIF = 'RISIKO_INHEREN_ADD_INPUT_KUALITATIF';
export const RISIKO_INHEREN_DELETE_INPUT_KUALITATIF = 'RISIKO_INHEREN_DELETE_INPUT_KUALITATIF';
export const RISIKO_INHEREN_GET_INPUT_KUALITATIF = 'RISIKO_INHEREN_GET_INPUT_KUALITATIF';
export const RISIKO_INHEREN_UPDATE_INPUT_KUALITATIF = 'RISIKO_INHEREN_UPDATE_INPUT_KUALITATIF';
