// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'SIGNIN_GITHUB_USER_SUCCESS';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'USER_DATA';
export const USER_TOKEN_SET = 'USER_TOKEN_SET';

//Parameter const
export const GET_ALL_PARAMETER_FAKTOR_TABLE = [];
export const GET_PARAMETER_FAKTOR = [];
export const PUT_PARAMETER_FAKTOR = [];
export const POST_PARAMETER_FAKTOR = [];
export const JENIS_NILAI_PARAM = [];
export const DELETE_PARAMETER_FAKTOR = 'DELETE_PARAMETER_FAKTOR';
export const STATUS_POST_PARAMETER_FAKTOR = 'STATUS_POST_PARAMETER_FAKTOR';
export const STATUS_PUT_PARAMETER_FAKTOR = 'STATUS_PUT_PARAMETER_FAKTOR';
export const STATUS_ALL_PARAMETER_FAKTOR_TABLE = 'STATUS_ALL_PARAMETER_FAKTOR_TABLE';
export const STATUS_ALL_PARAMETER_FAKTOR = 'STATUS_ALL_PARAMETER_FAKTOR';
export const COUNT_ALL_PARAMETER_FAKTOR = 'COUNT_ALL_PARAMETER_FAKTOR';

//JenisRisiko const
export const GET_ALL_RISKS = [];
export const GET_RISK = [];
export const POST_ALL_RISKS = [];
export const PUT_ALL_RISKS = [];
export const DELETE_ALL_RISKS = 'DELETE_ALL_RISK';
export const STATUS_POST_RISK = 'STATUS_POST_RISK';
export const STATUS_PUT_RISK = 'STATUS_PUT_RISK';
export const STATUS_ALL_RISKS = 'STATUS_ALL_RISKS';
export const COUNT_ALL_RISKS = 'COUNT_ALL_RISKS';
export const STATUS_ALL_RISK = 'STATUS_ALL_RISK';

//PeringkatRisiko const
export const GET_ALL_PERINGKAT_RISIKO = [];
export const GET_PERINGKAT_RISIKO = [];
export const POST_PERINGKAT_RISIKO = [];
export const PUT_PERINGKAT_RISIKO = [];
export const DELETE_PERINGKAT_RISIKO = 'DELETE_PERINGKAT_RISIKO';
export const STATUS_POST_PERINGKAT_RISIKO = 'STATUS_POST_PERINGKAT_RISIKO';
export const STATUS_PUT_PERINGKAT_RISIKO = 'STATUS_PUT_PERINGKAT_RISIKO';
export const STATUS_ALL_PERINGKAT_RISIKO = 'STATUS_PERINGKAT_RISIKO';
export const STATUS_ALL_PERINGKAT_RISIKO_TABLE = 'STATUS_PERINGKAT_RISIKO_TABLE';
export const COUNT_PERINGKAT_RISIKO = 'COUNT_PERINGKAT_RISIKO';

//JenisPenilaian const
export const GET_ALL_JENIS_PENILAIAN = [];
export const GET_JENIS_PENILAIAN = [];
export const POST_JENIS_PENILAIAN = [];
export const PUT_JENIS_PENILAIAN = [];
export const DELETE_JENIS_PENILAIAN = 'DELETE_JENIS_PENILAIAN';
export const STATUS_POST_JENIS_PENILAIAN = 'STATUS_POST_JENIS_PENILAIAN';
export const STATUS_PUT_JENIS_PENILAIAN = 'STATUS_PUT_JENIS_PENILAIAN';
export const STATUS_ALL_JENIS_PENILAIAN = 'STATUS_ALL_JENIS_PENILAIAN';
export const STATUS_ALL_JENIS_PENILAIAN_TABLE = 'STATUS_ALL_JENIS_PENILAIAN_TABLE';
export const COUNT_JENIS_PENILAIAN = 'COUNT_JENIS_PENILAIAN';

//RatioIndikator const
export const GET_ALL_RATIO_INDIKATOR_TABLE = [];
export const GET_RATIO_INDIKATOR = [];
export const GET_ALL_RATIO_INDIKATOR = [];
export const POST_RATIO_INDIKATOR = [];
export const PUT_RATIO_INDIKATOR = [];
export const DELETE_RATIO_INDIKATOR = 'DELETE_RATIO_INDIKATOR';
export const STATUS_POST_RATIO_INDIKATOR = 'STATUS_POST_RATIO_INDIKATOR';
export const STATUS_PUT_RATIO_INDIKATOR = 'STATUS_PUT_RATIO_INDIKATOR';
export const STATUS_ALL_RATIO_INDIKATOR = 'STATUS_ALL_RATIO_INDIKATOR';
export const STATUS_ALL_RATIO_INDIKATOR_TABLE = 'STATUS_ALL_RATIO_INDIKATOR_TABLE';
export const COUNT_RATIO_INDIKATOR = 'COUNT_RATIO_INDIKATOR';
